#!/usr/bin/env python3
from argparse import ArgumentParser
from sys import stdin, stderr
from tblgen import getRecords
import re

DESCRIPTION="""
This script takes information from RISCV.td and
generates three files

  BuiltinsRISCVET.def -- the set of builtin functions
      supported for Esperanto instructions
  IntrinsicsRISCET.def -- the LLVM intrinsics corresponding
      to Esperanto instructions.
  RISCVInstrInfoEsperantoPatterns.td -- DAG ISEL patterns
      to convert intrinsics to instructions.

Note where an "explicit" form of an instruction exists,
that is used for builtins and intrinsics rather than
the one with implicit register inputs.
"""

def main():
    ArgumentParser(DESCRIPTION).parse_args()

    summary = {}
    target_prefix = "riscv"

    def initOutput(fn):
        f = open(fn,"w")
        print("// Automatically generated by esperanto/python/intrinsics.py",
              file=f)
        return f;

    intrinsics = initOutput("IntrinsicsRISCVET.td")
    print(f'''\
let TargetPrefix = "{target_prefix}" in {{
def int_riscv_et_gather: Intrinsic<[llvm_anyvector_ty],
                                 [LLVMAnyPointerType<LLVMMatchType<0>>,
                                  llvm_v8i32_ty,  // 2 Index vector
                                  LLVMMatchType<0>, // 3  PassThrou
                                  llvm_i32_ty,    // 4 load extension type
                                  llvm_v8i1_ty], //  5 Mask
                                 [IntrReadMem, IntrArgMemOnly,
                                  IntrWillReturn, ImmArg<ArgIndex<3>>]>;

def int_riscv_et_scatter: Intrinsic<[],
                                 [llvm_anyvector_ty,
                                  LLVMAnyPointerType<LLVMMatchType<0>>,
                                  llvm_v8i32_ty, // 2 Index vector
                                  llvm_v8i1_ty], // 3 Mask
                                 [IntrWriteMem, IntrArgMemOnly,
                                  IntrWillReturn]>;
// Generate iota vector of length 8
def int_riscv_iota :
  GCCBuiltin<"__builtin_{target_prefix}_iota">,
  Intrinsic<[llvm_v8i32_ty],[], [IntrNoMem]>;
def int_riscv_hartid :
  GCCBuiltin<"__builtin_{target_prefix}_hartid">,
  Intrinsic<[llvm_i64_ty],[], [IntrNoMem]>;
''', file=intrinsics)
    builtins = initOutput("BuiltinsRISCVET.def")
    print(f'''\

// The format of this database matches clang/Basic/Builtins.def.

#if defined(BUILTIN) && !defined(TARGET_BUILTIN)
#   define TARGET_BUILTIN(ID, TYPE, ATTRS, FEATURE) BUILTIN(ID, TYPE, ATTRS)
#endif

BUILTIN(__builtin_riscv_iota,"v8i", "")
BUILTIN(__builtin_riscv_hartid,"Li", "")''', file=builtins)
    patterns = initOutput("RISCVInstrInfoEsperantoPatterns.td")


    records = getRecords();
    recordNames = { r.name for r in records }

    for r in records:
        if "HasEsperanto" not in r.getValue("Predicates"):
            continue
        if r.name + "_EX" in recordNames:
            continue
        # Exclude the stack pseudo ops
        # Exclude the MOVA operation as they are not modeled fully
        if any([r.name.startswith(p) for p in ["Stack", "MOVA"]]):
            continue
        name = r.name.lower()
        isExplicit = r.name.endswith("_EX")
        builtinName = name[:-3] if isExplicit else name
        mayLoad = r["mayLoad"]
        mayStore = r["mayStore"]
        isFloat = r.is_float()
        out_ops = r.getValue("OutOperandList")
        result = getTypes(name, out_ops, isFloat, maskType="llvm_i64_ty")
        in_ops = r.getValue("InOperandList")

        args = getTypes(name, in_ops, isFloat, maskType="llvm_i64_ty")
        addr = None
        if mayLoad or mayStore:
            addr = len(args) - (2 if isExplicit else 1)
            args[addr] = "llvm_ptr_ty"

        def getAttributes():
            attrs = getImmediates(in_ops)
            if mayLoad or mayStore:
                attrs.append("IntrArgMemOnly");
                if not mayStore:
                    attrs.append("IntrReadMem");
                if not mayLoad:
                    attrs.append("IntrWriteMem");
                attrs.append(f"NoCapture<ArgIndex<{addr}>>")
            else:
                attrs.append("IntrNoMem")
            return attrs

        attrs = getAttributes()
        attrs = ",".join(attrs)
        result = ",".join(result)
        args = ",".join(args)
        print(f"""\
def int_{target_prefix}_{builtinName} :
  GCCBuiltin<"__builtin_{target_prefix}_{builtinName}">,
  Intrinsic<[{result}],
            [{args}],
            [{attrs}]>;""", file=intrinsics);


        hasMask = any([op.startswith("MR") for op in in_ops + out_ops])
        if hasMask:
            result = getTypes(name, out_ops, isFloat, maskType="llvm_v8i1_ty")
            args = getTypes(name, in_ops, isFloat, maskType="llvm_v8i1_ty")
            if mayLoad or mayStore:
                args[addr] = "llvm_ptr_ty"

            result = ",".join(result)
            args = ",".join(args)
            print(f"""\
def int_{target_prefix}_{builtinName}_m :
  Intrinsic<[{result}],
            [{args}],
            [{attrs}]>;""", file=intrinsics);

        if result:
            builtinTypes = getBuiltinTypes(name, out_ops, isFloat)
        else:
            builtinTypes = "v"

        builtinTypes += getBuiltinTypes(name, in_ops, isFloat)
        # last argument a pointer?
        if mayLoad or mayStore:
            # always pointer to int32
            if isExplicit:
                # final argument is mask
                builtinTypes = builtinTypes[:-4] + "i*Li"
            else:
                assert builtinTypes.endswith("Li"), f"bad types {builtinTypes} for {r.name}"
                builtinTypes = builtinTypes[:-2] + "i*"

        print(f'BUILTIN(__builtin_{target_prefix}_{builtinName},'
              f'"{builtinTypes}", "")',
              file=builtins)

        def addType(op):
            ty, n = op.split(":",1)
            if ty in TXMap:
                return "timm:" + n
            assert not "imm" in ty, f"Missed TX for {ty}"
            if ty != "FPR256":
                return op
            ty = "v8f32" if isFloat else "v8i32"
            return f"({ty} {op})"
        def addTX(op):
            ty, n = op.split(":",1)
            tx = TXMap.get(ty,None)
            if tx:
                return f"({tx} {n})"
            return n
        intr_args = [ addType(op) for op in in_ops ]
        if name.startswith("fcvt_ps_pw"):
            intr_args[1] = "(v8i32 FPR256:$rs1)"
        elif name.startswith("fcvt_pw"):
            intr_args[0] = "(v8i32 FPR256:$in)"
        intr_args = ", ".join(intr_args)
        intr_out = [ addTX(op) for op in in_ops ]
        intr_out = ", ".join(intr_out)
        print(f'def : EspPat<(int_{target_prefix}_{builtinName} {intr_args}),',
              f'({r.name} {intr_out})>;', file=patterns)
        if hasMask:
            print(f'def : EspPat<(int_{target_prefix}_{builtinName}_m {intr_args}),',
                  f'({r.name} {intr_out})>;', file=patterns)

    print(f'}} // TargetPrefix = "{target_prefix}"',file=intrinsics)

    print(f'''\

#undef BUILTIN
#undef TARGET_BUILTIN''', file=builtins)


intTypeMap = { "GPR" : "llvm_i64_ty" ,
               "MR" : "llvm_i64_ty",
               "MR0" : "llvm_i64_ty",
               "FPR32" : "llvm_f32_ty",
               "frmarg" : "llvm_i64_ty",
               "ofrmarg" : "llvm_i64_ty",
               "uimm3" : "llvm_i64_ty",
               "uimm5" : "llvm_i64_ty",
               "FPR256" : "llvm_v8i32_ty" }
floatTypeMap = intTypeMap.copy()
floatTypeMap["FPR256"] = "llvm_v8f32_ty"


TXMap = {  "frmarg" : "LO3",
           "ofrmarg" : "LO3",
           "uimm3" : "LO3",
           "uimm4" : "LO4",
           "uimm5" : "LO5",
           "uimm8" : "LO8",
           "simm10" : "LO10s",
           "simm12" : "LO12s",
           "simm20" : "LO20s",
           "uimm20_lui" : "LO20",
}

def getTypes(iname, ops, isFloat, maskType):
    typeMap = floatTypeMap if isFloat else intTypeMap
    typeList = []
    for op in ops:
        ty,name = op.split(":")
        if name.startswith("$imm"):
            rty = "llvm_i32_ty"
        elif ty.startswith("MR"):
            rty = maskType
        else:
            rty = typeMap.get(ty,None)
            if rty is None:
                print("invalid type",op,file=stderr)
                exit(1)
        typeList.append(rty)

    if len(typeList) == 1:   # outputs?
        if iname.startswith("fcvt_pw"):
            typeList = ["llvm_v8i32_ty"]
    else: # inputs
        if iname.startswith("fcvt_ps_pw"):
            typeList[1] = "llvm_v8i32_ty"
        elif iname.startswith("fcvt_pw"):
            typeList[0] = "llvm_v8i32_ty"
    return typeList


def getImmediates(ops):
    imms = []
    for idx,op in enumerate(ops):
        ty,name = op.split(":")
        if not (name.startswith("$imm") or name == "$idx" or name == "$rm"):
            continue
        imms.append(f"ImmArg<ArgIndex<{idx}>>")
    return imms

builtinIntTypeMap = {
    "GPR" : "Li" ,
    "MR" : "Li",
    "MR0" : "Li",
    "FPR32" : "f",
    "frmarg" : "IULi",
    "ofrmarg" : "IULi",
    "uimm3" : "IULi",
    "uimm5" : "IULi",
    "FPR256" : "V8i",
}
builtinFloatTypeMap = builtinIntTypeMap.copy()
builtinFloatTypeMap["FPR256"] = "V8f"


def getBuiltinTypes(iname, ops, isFloat):
    typeMap = builtinFloatTypeMap if isFloat else builtinIntTypeMap
    typeList = []
    for op in ops:
        ty,name = op.split(":")
        if name.startswith("$imm"):
            rty = "Ii"
        else:
            rty = typeMap.get(ty,None)
            if rty is None:
                print("invalid type",op,file=stderr)
                exit(1)
        typeList.append(rty)

    if len(typeList) == 1:   # outputs?
        if iname.startswith("fcvt_pw"):
            typeList = ["V8i"]
    else: # inputs
        if iname.startswith("fcvt_ps_pw"):
            typeList[1] = "V8i"
        elif iname.startswith("fcvt_pw"):
            typeList[0] = "V8i"

    return "".join(typeList)


if __name__ == "__main__":
    main()
