include:
  - project: esperantotech/software/gitlab-ci-common
    ref: 1be8a1ec31da665910e1b2b193fcfa1d05866299
    file:
      - /rules/generic-workflow-conan.yaml
      - /jobs/generic-k8s-job.yaml
      - /pods/medium-pod.yaml
      - /pods/large-pod.yaml
      - /jobs/check-top-of-master-template.yaml
      - /jobs/sw-platform-trigger-template.yaml

  - project: esperantotech/software/gitlab-ci-common
    ref: master
    file:
      - 'jobs/conan-jobs.yaml'

stages:
  - generate_build
  - build
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: none

# Only run job in these cases:
# - if it's a tag pipeline
# - if there is a commit pushed or merged to the default branch (pre-release)
.release_job:
  rules:
    - &release_job_rule
      if: $CI_COMMIT_TAG || ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)

# Only run job in these cases:
# - if it's a tag pipeline
# - if there is a commit pushed or merged to the default branch (pre-release)
# - if there is a MR open (pre-release, unstable)
.release_or_development_job:
  rules:
    - &release_or_development_job_rule
      if: $CI_COMMIT_TAG || ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH) || ($CI_PIPELINE_SOURCE == "merge_request_event")

# Only run job in these cases:
# - if there is a MR open
.development_job:
  rules:
    - &development_job_rule
      if: ($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH)



###############################################################################
###############################################################################
###############################################################################

generate_build:conan:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: generate_build
  needs:
    - job: check-on-top-of-master
      optional: true
  rules:
    - *release_or_development_job_rule
  variables:
    TIMEOUT: 15m
    CMD_BUILD: |
      cd esperanto
      python3 -m pip install "ecpt>=2.0.0,<3.0.0" --index-url https://sc-artifactory1.esperanto.ai/artifactory/api/pypi/pypi-virtual/simple
      python3 -m ci_build ../conanfile.py
      cat <<EOT >> build_pipeline.yml
      variables:
        GIT_SUBMODULE_STRATEGY: recursive
      EOT
      cd -
      git status
  artifacts:
    expire_in: 1d
    paths:
      - esperanto/build_pipeline.yml

###############################################################################
###############################################################################
###############################################################################

build:conan:
  stage: build
  extends:
    - .exec_maybe_interactively
  needs:
    - generate_build:conan
  rules:
    - *release_or_development_job_rule
  trigger:
    include:
      - artifact: esperanto/build_pipeline.yml
        job: generate_build:conan
    strategy: depend

###############################################################################
###############################################################################
###############################################################################

.invoke_unit_tests:
  extends:
    - .pod_large
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: test
  needs:
    - job: check-on-top-of-master
      optional: true
  rules:
    - *development_job_rule
  variables:
    KUBERNETES_MEMORY_LIMIT: 128Gi
    TIMEOUT: 3h

test:llvm:
  extends:
    - .invoke_unit_tests
  stage: test
  parallel:
    matrix:
      - BUILD_TYPE:
        - Debug
        - Release
  script:
    - echo BUILD_TYPE=$BUILD_TYPE
    - mkdir build
    - cd build
    - cmake ../llvm -G Ninja
      -DLLVM_ENABLE_PROJECTS="clang;compiler-rt"
      -DCMAKE_INSTALL_PREFIX=$HOME/opt/llvm
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      -DCMAKE_C_COMPILER=gcc
      -DCMAKE_CXX_COMPILER=g++
      -DCMAKE_CXX_FLAGS=-DESPERANTO
      -DLLVM_TARGET_ARCH=riscv64
      -DLLVM_TARGETS_TO_BUILD="RISCV"
    - cmake --build .
    - cmake --build . --target check-llvm-analysis-costmodel-riscv
    - cmake --build . --target check-llvm-codegen-riscv
    - cmake --build . --target check-llvm-debuginfo-riscv
    - cmake --build . --target check-llvm-mc-disassembler-riscv
    - cmake --build . --target check-llvm-mc-riscv
    - cmake --build . --target check-llvm-object-riscv
    - cmake --build . --target check-llvm-tools-llvm-dwarfdump-riscv
    - cmake --build . --target check-llvm-tools-llvm-objdump-elf-riscv
    - cmake --build . --target check-llvm-tools-llvm-readobj-elf-riscv
    - cmake --build . --target check-llvm-transforms-atomicexpand-riscv
    - cmake --build . --target check-llvm-transforms-constanthoisting-riscv
    - cmake --build . --target check-llvm-transforms-simplifycfg-riscv

###############################################################################
###############################################################################
###############################################################################

test:conan:
  extends:
    - .invoke_unit_tests
  stage: test
  script:
    - conan install . -pr:b default -pr:h
      linux-ubuntu18.04-x86_64-gcc7-release
      --build missing
      -o esperanto-llvm:with_clang=True
      -o esperanto-llvm:with_compiler-rt=True
      -o esperanto-llvm:targets=RISCV
    - echo Hello Pau! Put here your build and test recipe
    #- cmake --preset release
    #- cmake --build --preset release
    #- cmake --build .
    #- cmake --build . --target check-llvm-analysis-costmodel-riscv
    #- cmake --build . --target check-llvm-codegen-riscv
    #- cmake --build . --target check-llvm-debuginfo-riscv
    #- cmake --build . --target check-llvm-mc-disassembler-riscv
    #- cmake --build . --target check-llvm-mc-riscv
    #- cmake --build . --target check-llvm-object-riscv
    #- cmake --build . --target check-llvm-tools-llvm-dwarfdump-riscv
    #- cmake --build . --target check-llvm-tools-llvm-objdump-elf-riscv
    #- cmake --build . --target check-llvm-tools-llvm-readobj-elf-riscv
    #- cmake --build . --target check-llvm-transforms-atomicexpand-riscv
    #- cmake --build . --target check-llvm-transforms-constanthoisting-riscv
    #- cmake --build . --target check-llvm-transforms-simplifycfg-riscv


###############################################################################
###############################################################################
###############################################################################

on_success:promote:
  extends:
    - .pod_medium
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: deploy
  needs:
    - build:conan
    - job: test:conan
      optional: true
    - job: test:llvm
      optional: true
  rules:
    - *release_job_rule
  variables:
    PYTHONIOENCODING: utf-8
    CMD_BUILD: |
      cd esperanto
      python3 -m pip install "ecpt>=2.0.0,<3.0.0" --index-url https://sc-artifactory1.esperanto.ai/artifactory/api/pypi/pypi-virtual/simple
      python3 -m ci_promote
